[versions]
junit = "5.9.1"

[libraries]
kotlinTestJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter-engine" }
junitApi = { module = "org.junit.jupiter:junit-jupiter-api" }
junitParams = { module = "org.junit.jupiter:junit-jupiter-params" }
